coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.04%
    patch:
      default:
        target: 100%
        threshold: 0%

codecov:
  notify:
    wait_for_ci: true
    after_n_builds: 3
