package:
  name: openpathsampling-full
  version: "0.9.2"

requirements:
  run:
    - python
    - numpy
    - scipy
    - pandas
    - netcdf4
    - openmm
    - openmmtools
    - jupyter
    - mdtraj
    - svgwrite
    - networkx
    - matplotlib
    - ujson
    - pyemma

test:
  imports:
    - openpathsampling-dev


about:
  home: http://github.com/openpathsampling/openpathsampling
  license: LGPL 2.1 or later
  summary: 'OpenPathSampling: A python package to do path sampling simulations'
